### ISSUE TITLE
Tighter validation on ID

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#225]
We have a list of valid organ codes, so the regex could be tighter. Currently in level-1.yaml:
```
    name: tissue_id
    description: HuBMAP Display ID of the assayed tissue.
    constraints:
      pattern: '[A-Z]+[0-9]+(-[A-Z0-9]+)+'
```
