### ISSUE TITLE
sequencing_read_format pattern?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#303]
Follow up to 302... This was going to be committed:
```
- name: sequencing_read_format
  description: Number of sequencing cycles in Read1, i7 index, i5 index, and Read2
  constraints:
   pattern: '[Ri]?\d+(/[Ri]?\d+)+'
```
The regex I suggested is more general than what is described: @cebriggs7135 : 
- Is this format suggestion something that's coming to you from the labs, or is it our invention? The `R` and `i` seem to be making something more complicated that's really just a list of 4 numbers...
- From the description, it sounds like there will be precisely 4 numbers; Is that true?

If discussing on slack or zoom is better, let's do that.
