### ISSUE TITLE
Change af and stained directory schema: .tif and .tiff extensions should be allowed

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#710]
> - Does this change have buy-in from other groups providing the same kind of data?

Limited to ".tif" in the scheme is not correct. We are specifying that microscopy is packaged in OME-TIFF format which abbreviates `Open Microscopy Environment - Tagged Image File Format`. While `ome.tif` is current and acceptable, `ome.tiff` is should also be allowed as this is the default specification by `bioformats`, progenitors of OME-TIFF (see links below). 

> - Can you quote or reference any outside documentation that motivates this change?

https://docs.openmicroscopy.org/bio-formats/6.6.1/formats/ome-tiff.html?highlight=ome%20tiff%20specification
https://docs.openmicroscopy.org/ome-model/6.2.2/ome-tiff/specification.html

> - Is this change backward compatible, or does it make validation more stringent?

Yes it should be. A wildcard in the regex should allow both `ome.tif` and `ome.tiff`, or if only one is preferred, `ome.tiff` should be preferred. 

@icaoberg will evaluate this request, and if it can move forward,
will file a PR for @pdblood to review,
and @mccalluc will make sure tests pass before merging.

### one solution

https://github.com/hubmapconsortium/ingest-validation-tools/blob/b3c065b871c8f060ef7a7be27b3bb3bdae143260/src/ingest_validation_tools/directory-schemas/af.yaml#L12

```yaml
-
  pattern: 'processedMicroscopy/[^/]+_preIMS_images/[^/]+\.ome\.tif*'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the autofluorescence microscopy linked to IMS experiment'

```
