### ISSUE TITLE
Change af directory schema: don't specify a "pre" imaging modality for AF

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#711]
> - Does this change have buy-in from other groups providing the same kind of data?

Vanderbilt TMC is the only one collecting this data. The current specification requires three pieces of data, when in reality, only one will ever be present, causing failures across the board for submission validation. below is the current schema, all patterns are obligatory for each `af` entry. This pattern expects a preCODEX AF image, a preMxIF AF and a preIMS AF data PER metadata entry, which is impossible experimentally. 

```yaml
# A dataset consists of a single autofluorescence microscopy run, and  
# a set of transformation files that are useful for other
# related datasets. (Vanderbilt)

-
  pattern: 'processedMicroscopy/[^/]+_preMxIF_images/[^/]+\.ome\.tif'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the autofluorescence microscopy linked to MxIF experiment'
-
  pattern: 'processedMicroscopy/[^/]+_preMxIF_transformations/[^/]+\.txt'
  description: 'Transformations to MxIF (related) data'
-
  pattern: 'processedMicroscopy/[^/]+_preIMS_images/[^/]+\.ome\.tif'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the autofluorescence microscopy linked to IMS experiment'
-
  pattern: 'processedMicroscopy/[^/]+_preIMS_transformations/[^/]+\.txt'
  description: 'Transformations to IMS (related) data'
-
  pattern: 'processedMicroscopy/[^/]+_preCODEX_images/[^/]+\.ome\.tif'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the autofluorescence microscopy linked to CODEX experiment'
-
  pattern: 'processedMicroscopy/[^/]+_preCODEX_transformations/[^/]+\.txt'
  description: 'Transformations to CODEX (related) data'
```

The pre modality here doesn't actually matter a preCODEX dataset is identical to a preAF dataset in terms of associated files. the "pre"-modality just informs the linked modality (which is more appropriately obtained by section number in the sample id). 

### Suggestion
```yaml
-
  pattern: 'processedMicroscopy/[^/]+_images/[^/]+\.ome\.tif*'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the autofluorescence microscopy'
-
  pattern: 'processedMicroscopy/[^/]+_transformations/[^/]+\.txt'
  description: 'Transformations to IMS (related) data'
```

This will cover all modalities pre-acquisition autofluorescence. 

> - Can you quote or reference any outside documentation that motivates this change?

I developed the AF workflow for microscopy integration.

> - Is this change backward compatible, or does it make validation more stringent?

Yes, it would be backwards compatible. 

@icaoberg will evaluate this request, and if it can move forward,
will file a PR for @pdblood to review,
and @mccalluc will make sure tests pass before merging.
