### ISSUE TITLE
Change stained directory schema: current schema is specific to PAS stain, not generic to stained microscopy

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#712]
> - Does this change have buy-in from other groups providing the same kind of data?

If others have uploaded stained microscopy, I am not sure but it is a very common assay so I expect eventually they might. However, the current schema is tied to Vanderbilt by specifying `PAS` in the schema, which is an abbreviation for a periodic acid-Schiff, a specific staining assay. Others may use H&E, trichrome, or an endless list of others while producing very similar microscopy image outputs. The `metadata` schema is generic, however.

### current
```yaml
-
  pattern: 'processedMicroscopy/[^/]+_PAS_images/[^/]+ome\.tif'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the PAS microscopy experiment'
-
  pattern: 'processedMicroscopy/[^/]+_PAS_transformations/[^/]+\.txt'
  description: 'Transformations to PAS (related) data'
```

### suggested
```yaml
-
  pattern: 'processedMicroscopy/[^/]+_images/[^/]+ome\.tif*'
  description: 'OME TIFF files (multichannel, multi-layered, image pyramids) produced by the stained microscopy experiment'
-
  pattern: 'processedMicroscopy/[^/]+_transformations/[^/]+\.txt'
  description: 'Transformations to stained microscopy data'
```

> - Can you quote or reference any outside documentation that motivates this change?

This wikipedia article lists 12 specific staining assays for reference (there are many more):
https://en.wikipedia.org/wiki/Staining

> - Is this change backward compatible, or does it make validation more stringent?

It will be if the suggestion above is implemented.

@icaoberg will evaluate this request, and if it can move forward,
will file a PR for @pdblood to review,
and @mccalluc will make sure tests pass before merging.
