### ISSUE TITLE
Mixed assay types should error? Or not?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#735]
A single TSV could include multiple assay types:
```
- name: assay_type
  constraints:
    enum:
      - LC-MS (metabolomics)
      - LC-MS/MS (label-free proteomics)
      - MS (shotgun lipidomics)
```
but Joel writes:
> This has never been done, however.  All the metadata.tsv files I've seen have been for a single assay type, and in fact I'd want to watch carefully if we got one which mixed LC-MS and LC-MS/MS for example.  Handling multiple separate metadata.tsv files is fully supported, however.

but then Ivan says:
> Agree not a priority. But I am in a meeting with Chris Briggs  and most of the PMs from the different data providers and we just said they could. So we might see this in the near future.
