### ISSUE TITLE
scrnaseq-v2.yaml version wrong

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#741]
```
-
  heading: Shared by all types
  name: version
  description: Version of the schema to use when validating this metadata.
  constraints:
    enum:
      - '1'
```

Should be 2.
